trigger: none

variables:
  nlw_token: $(secret_nlw_token)
  license_server_url: https://neoload-rest.saas.neotys.com:443/nts
  license_server_login: $(secret_license_server_login)
  license_id: $(secret_license_id)
  zone_code: 9h2lZ
  wksp: $(Pipeline.Workspace)/s

resources:
  containers:
  - container: neoload_ctrl
    image: paulsbruce/neoload-controller-azure:6.10
    env: { MODE: Managed, NEOLOADWEB_TOKEN: $(nlw_token), ZONE: $(zone_code) }
  - container: lg1
    image: neotys/neoload-loadgenerator:6.10
    env: { NEOLOADWEB_TOKEN: $(nlw_token), ZONE: $(zone_code) }
    options: -p 7101:7100

pool:
  vmImage: 'ubuntu-16.04'

container: neoload_ctrl

services:
  lg1: lg1

steps:
- bash: |
    mkdir neoload-report
    echo "lg1:7101@Docker" > $(wksp)/LGs_pop1.txt
        
- bash: |
    /home/neoload/neoload/bin/NeoLoadCmd \
      -project $(wksp)/neoload_project/project.yaml \
      -launch sanityScenario \
      -testResultName 'Azure sanityScenario' \
      -description 'Basic sanity check against Google' \
      -NTS $(license_server_url) -NTSLogin $(secret_license_server_login) \
      -leaseLicense $(secret_license_id):50:1 \
      -report $(wksp)/neoload-report/report.html,$(wksp)/neoload-report/report.xml \
      -SLAJUnitResults $(wksp)/neoload-report/junit-sla-results.xml \
      -L pop1=$(wksp)/LGs_pop1.txt \
      -exitCodeFailIgnore \
      -noGUI \
      -nlweb \
      -nlwebToken $(nlw_token)

# above could be improved via custom task: https://docs.microsoft.com/en-us/azure/devops/extend/develop/integrate-build-task?view=azure-devops

- task: CopyFiles@2
  inputs:
    contents: 'neoload-report/**'
    targetFolder: $(System.DefaultWorkingDirectory)

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '$(System.DefaultWorkingDirectory)/neoload-report/junit-sla-results.xml'
    failTaskOnFailedTests: true