trigger:
  - master

variables:
  nlw_token: $(secret_nlw_token)

resources:
  containers:
  - container: neoload_ctrl
    image: neotys/neoload-controller:latest
    env: { MODE: Managed, NEOLOADWEB_TOKEN: $(nlw_token) }
  - container: lg1
    image: neotys/neoload-loadgenerator:latest
    env: { NEOLOADWEB_TOKEN: $(nlw_token) }
    options: -p 7101:7100

pool:
  vmImage: 'ubuntu-16.04'

container: neoload_ctrl

services:
  lg1: lg1

steps:
- bash: |
    echo hello
    pwd
    apt install -y net-tools
    nslookup lg1
