name: NeoLoadAzureYAML

sla_profiles:
- name: external_calls_sla
  thresholds:
  - avg-resp-time warn >= 100ms fail >= 500ms per interval
  - error-rate warn >= 2% fail >= 5% per test

user_paths:
- name: samples_home
  actions:
    steps:
    - transaction:
        name: Sample Demo Home
        steps:
        - think_time: 1s
        - request:
            url: http://sampledemo.neotys.com
            sla_profile: external_calls_sla

populations:
- name: pop1
  user_paths:
  - name: samples_home

scenarios:
- name: sanityScenario
  populations:
  - name: pop1
    rampup_load:
      min_users: 1
      max_users: 50
      increment_users: 1
      increment_every: 2s
      duration: 2m
